name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [bilibili-live, l4d2-query, splatoon3-query]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: wrapper
        build-root-directory: ${{ matrix.dir }}

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: buildPlugin
        build-root-directory: ${{ matrix.dir }}
        
    - name: Get gradle version action
      uses: thecodemonkey/action-get-gradle-version@v1.0
      id: getversion
      with:
        file: ${{ matrix.dir }}/build.gradle.kts
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.dir }}-plugin-${{ steps.getversion.outputs.version }}.mirai2.jar
        path: ${{ matrix.dir }}/build/mirai/*.jar